<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.1.0</Version>
    <NativeLibraryVersion>1.1.4</NativeLibraryVersion>
    <SerialPortStreamVersion>3.0.5</SerialPortStreamVersion>
  </PropertyGroup>
</Project>

